using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace SchoolSystem.Models
{
    public class Course
    {

        //primary key property
        [Key]
        // StudentId will NOT be auto-generated by the database
        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        public int CourseId { get; set; }
        public string CourseName { get; set; }
        public string RoomNumber { get; set; }
        public int MaxCapacity { get; set; }
    }
}
