using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
namespace SchoolSystem.Models
{
    public class SchoolSupplies
    {
        //primary key property
        [Key]
        // StudentId will NOT be auto-generated by the database
        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        public int ItemId { get; set; }
        public string ItemName { get; set; }
        public decimal Price { get; set; }
        public int QuantityAvaliable { get; set; }

    }
}
