using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace SchoolSystem.Models
{
    public class Student
    {
        //primary key property
        [Key]
        // StudentId will NOT be auto-generated by the database
        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        public int StudentId { get; set; }
        public string FullName { get; set; }
        public int Age { get; set; }
        public string GradeLevel { get; set; }
    }

}
